# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1

# Workflows orchestrate a set of jobs to be run;
workflows:
  version: 2
  build-test:
    jobs:
      - build-and-test

jobs:

  build-and-test:
    macos:
      xcode: 11.6.0 # Specify the Xcode version to use

    steps:
      - checkout
      # pre-start the simulator to prevent timeouts
      - run:
          name: Pre-start Simulator
          command: xcrun instruments -w "iPhone 8 (13.0) [" || true
      
      - run:
          name: Pod install
          command: pod install

      - run:
          name: lipo test
          command: make archive_framework
